---
- hosts: all
  become: true
  tasks:

  - name: install python3
    apt:
      name: python3
      
  - name: install pip3
    apt:
      name: python3-pip   
      update_cache: yes 
      state: present
      

